FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.16-openshift-4.8 AS builder
WORKDIR /go/src/github.com/kubernetes-sigs/vsphere-csi-driver
COPY . .
RUN make build # TODO: build only driver

FROM registry.ci.openshift.org/ocp/4.8:base
RUN mkdir -p config
ADD pkg/apis/cnsoperator/config/cnsregistervolume_crd.yaml /config/
ADD pkg/apis/cnsoperator/config/cnsfileaccessconfig_crd.yaml /config/
ADD pkg/internal/cnsoperator/config/cnsfilevolumeclient_crd.yaml /config/
COPY --from=builder /go/src/github.com/kubernetes-sigs/vsphere-csi-driver/.build/bin/syncer.linux_amd64  /usr/bin/vmware-vsphere-csi-driver-syncer
ENTRYPOINT ["/usr/bin/vmware-vsphere-csi-driver-syncer"]
